# Site
name: "سفرنامه"
title: "سفرنامه"
description: "سفرنامه"
logo: 'assets/images/my.jpg'
favicon: 'assets/images/favicon.png'
baseurl: ''
url: "https://travel.mhkarami97.ir"
#google_analytics: ''
#disqus: ''
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive_image.html
  sizes:
    - width: 320
    - width: 480
    - width: 800
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      
comments: false
   
giscus:
  repo: "MHKarami97/travel"
  repo-id: "MDEwOlJlcG9zaXRvcnkzNTE1MzIwODM="
  category: "General"
  category-id: "DIC_kwDOFPP0M84B-Ro6"
  mapping: "pathname"
  reaction-enabled: "1"
  theme: "light"
  crossorigin: "anonymous"  
  
google_analytics: "G-2KGKGYQR60"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2KGKGYQR60"
    anonymize_ip: false # default  

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]